sudo: required
language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - pip install flake8
  - pip install hint
  - python setup.py install
  - chmod 777 tests/test.sh
script: flake8 && ./tests/test.sh && hint README.md
